#!/usr/bin/env bash

# LOAD SCRIPTING ADDITIONS
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# COLORS
INSERT="0xFF$(awk -F '[#]' '/color4/{print $2}' ~/.Xresources)"
ACTIVE="0xFF$(awk -F '[#]' '/color2/{print $2}' ~/.Xresources)"
INACTIVE="0xFF$(awk -F '[#]' '/background/{print $2}' ~/.Xresources)"

# BAR HEIGHT
BAR_HEIGHT=$(sketchybar -m --query bar | jq -r '.height')

# SETUP SPACES
source "${HOME}"/.config/bin/helper && create_spaces 6

GENERAL=(
    external_bar main:"${BAR_HEIGHT}":0
    split_type auto
    split_ratio 0.5
    auto_balance off
    insert_feedback_color "${INSERT}"
)

WINDOWS=(
    window_placement second_child
    window_topmost on
    window_zoom_persist on
    window_shadow float
    window_opacity on
    active_window_opacity 1.0
    normal_window_opacity 0.9
    window_animation_duration 0.0
    window_origin_display focused
    window_opacity_duration 0.15
)

BORDERS=(
    window_border on
    window_border_blur on
    window_border_hidpi on
    window_border_width 2
    window_border_radius 12
    active_window_border_color "${ACTIVE}"
    normal_window_border_color "${INACTIVE}"
)

LAYOUT=(
    layout bsp
    top_padding 6
    bottom_padding 6
    left_padding 6
    right_padding 6
    window_gap 10
)

MOUSE=(
    mouse_modifier ctrl
    mouse_action1 move
    mouse_action2 resize
    mouse_drop_action swap
    mouse_follows_focus on
    focus_follows_mouse autoraise
)

yabai -m config "${GENERAL[@]}"
yabai -m config "${WINDOWS[@]}"
yabai -m config "${BORDERS[@]}"
yabai -m config "${LAYOUT[@]}"
yabai -m config "${MOUSE[@]}"

# SPACE LABELS
LABELS=(
    main
    comms
    work
    media
    misc
    scratch
)

for (( i=1; i<="${#LABELS[@]}"; i++ )); do 
    yabai -m space "${i}" --label "${LABELS[(( $i - 1 ))]}"
done

# RULES
UNMANAGED=(
    Calculator
    Software Update
    Dictionary
    zoom.us
    Photo Booth
    Archive Utility
    Python
    LibreOffice
    App Store
    Steam
    Alfred
    Activity Monitor
    Finder
    Authy
    Bitwarden
    System Preferences
    System Settings
    ScanSnap
)

for (( i=1; i<="${#UNMANAGED[@]}"; i++ )); do 
    yabai -m rule --add label="unmanage_${UNMANAGED[(( $i - 1 ))]}" app="^${UNMANAGED[(( $i - 1 ))]}.*$" manage=off
done

# # TOPMOST
# yabai -m config --space 1 window_topmost on 
# yabai -m config --space 2 window_topmost off layout stack 
# yabai -m config --space 3 window_topmost off layout stack 
# yabai -m config --space 4 window_topmost on 
# yabai -m config --space 5 window_topmost on 
# yabai -m config --space 6 window_topmost off layout float


# Rules
# yabai -m rule --add label="Unmanged" app="^(Calculator|Software Update|Dictionary|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor|Finder|Authy|Bitwarden|System Preferences|System Settings|ScanSnap.*)$" manage=off
# yabai -m rule --add label="comms" app="^(Microsoft Teams|Mail|Messages|Spark|Mail|Discord)$" layer=normal space=comms opacity=1.0
# yabai -m rule --add label="DialpadSplash" app="Dialpad" title=".*- Loading.*$" manage=off layer=below space=scratch opacity=0.0
# yabai -m rule --add app="Dialpad" space=comms layer=normal opacity=1.0
# yabai -m rule --add app="^Music$" space=media
# yabai -m rule --add label="LayerAboveApp" app="^(Finder|ScanSnap.*)$" layer=above
# yabai -m rule --add label="LayerAboveTitle" title="^(Colors.*|Character Viewer|MiniPlayer)$" manage=off layer=above
# yabai -m rule --add label="Sticky" app="^(Authy Desktop|Bitwarden|System Preferences|System Settings)$" sticky=on
# yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
# yabai -m rule --add label="Spark" app="^Spark$" title!="^Spark - .*$" manage=off sticky=on layer=normal
# yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
# yabai -m rule --add label="wallpaper" app="kitty" title="^Wallpaper$" manage=off sticky=on
# yabai -m rule --add app="^LinkedNotesUIService$" title="^Window$" border=off manage=off layer=normal
# yabai -m rule --add app="^Screens$" title!="Screens Library" manage=off native-fullscreen=on
# yabai -m rule --add app="^Microsoft Remote Desktop$" title!="Microsoft Remote Desktop" native-fullscreen=on
# yabai -m rule --add app="^Microsoft Remote Desktop$" title="Microsoft Remote Desktop" manage=off layer=normal
# yabai -m rule --add app="^Screen Sharing$" title="^Screen Sharing$" manage=off native-fullscreen=on
# yabai -m rule --add app="kitty" title="KUAKE" manage=off grid=8:8:0:0:8:3  layer=above border=on
# yabai -m rule --add app="kitty" title="Wallpaper" manage=off grid=8:8:0:5:8:3  layer=above border=on sticky=on opacity=0.85
# yabai -m rule --add label="Firefox" app="Firefox" title="^(Opening|Set Desktop Background|VM.*|QEMU.*|.*noVNC)$" manage=off layer=above

# # Signals
# yabai -m signal --add event=window_created app="Firefox" title!="— Private Browsing$" action="source $HOME/.config/bin/helper && auto_stack Firefox"
# yabai -m signal --add event=window_created app="Firefox" title="^VM [0-9]+" action="source $HOME/.config/bin/helper && create_spaces a noVNC $YABAI_WINDOW_ID"
# # yabai -m signal --add event=window_destroyed app="Firefox" title="- noVNC$" action="yabai -m space noVNC --destroy"
# yabai -m signal --add event=window_created action="sketchybar -m --trigger yabai_window &> /dev/null"
# yabai -m signal --add event=window_destroyed action="sketchybar -m --trigger yabai_window &> /dev/null"
# yabai -m signal --add event=window_focused action="sketchybar -m --trigger yabai_window &> /dev/null"
# yabai -m signal --add event=space_changed action="sketchybar -m --trigger yabai_window &> /dev/null;"
# yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger yabai_window &> /dev/null"
# yabai -m signal --add event=window_created app="Code" action="source $HOME/.config/bin/helper && auto_stack Code"
# yabai -m signal --add event=window_destroyed action="yabai -m window --focus mouse||yabai -m window --focus next"

# # Teams Notification Fix
# yabai -m signal --add                                \
# event=application_activated                          \
# app="^Microsoft Teams$"                              \
# action="${HOME}/.config/bin/yabai_teams_helper.sh"

# yabai -m signal --add                                \
# event=window_focused                                 \
# app="^Microsoft Teams$"                              \
# title="^Microsoft Teams Notification$"               \
# action="${HOME}/.config/bin/yabai_teams_helper.sh"
