#!/usr/bin/env bash

# TODO: Set `window_zoom_persist on` when released

# LOAD SCRIPTING ADDITIONS
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# COLORS
INSERT="0xFF$(awk -F '[#]' '/color4/{print $2}' ~/.Xresources)"
ACTIVE="0xFF$(awk -F '[#]' '/color2/{print $2}' ~/.Xresources)"
INACTIVE="0xFF$(awk -F '[#]' '/background/{print $2}' ~/.Xresources)"

# BAR HEIGHT
BAR_HEIGHT=$(sketchybar -m --query bar | jq -r '.height')

# SETUP SPACES
source "${HOME}"/.config/bin/helper && create_spaces 6

GENERAL=(
    external_bar main:"${BAR_HEIGHT}":0
    split_type auto
    split_ratio 0.5
    auto_balance off
    insert_feedback_color "${INSERT}"
)

WINDOWS=(
    window_placement second_child
    window_topmost on
    window_shadow float
    window_opacity on
    active_window_opacity 1.0
    normal_window_opacity 0.9
    window_animation_duration 0.0
    window_origin_display focused
    window_opacity_duration 0.15
)

BORDERS=(
    window_border on
    window_border_blur on
    window_border_hidpi on
    window_border_width 2
    window_border_radius 12
    active_window_border_color "${ACTIVE}"
    normal_window_border_color "${INACTIVE}"
)

LAYOUT=(
    layout bsp
    top_padding 6
    bottom_padding 6
    left_padding 6
    right_padding 6
    window_gap 10
)

MOUSE=(
    mouse_modifier ctrl
    mouse_action1 move
    mouse_action2 resize
    mouse_drop_action swap
    focus_follows_mouse autoraise
)

yabai -m config "${GENERAL[@]}"
yabai -m config "${WINDOWS[@]}"
yabai -m config "${BORDERS[@]}"
yabai -m config "${LAYOUT[@]}"
yabai -m config "${MOUSE[@]}"

# SPACE LABELS
LABELS=(
    main
    comms
    work
    media
    misc
    scratch
)

for (( i=1; i<="${#LABELS[@]}"; i++ )); do 
    yabai -m space "${i}" --label "${LABELS[(( $i - 1 ))]}"
done

# SPACE LAYOUTS
yabai -m config --space comms layout stack window_opacity off
yabai -m config --space media layout stack window_opacity off
yabai -m config --space scratch layout float

# RULES
UNMANAGED=(
    Activity Monitor
    Alfred
    App Store
    Archive Utility
    Authy
    Bitwarden
    Calculator
    Dictionary
    Finder
    LibreOffice
    Microsoft Remote Desktop
    Photo Booth
    Python
    ScanSnap
    Screens
    Screen Sharing
    Software Update
    Steam
    System Information
    System Preferences
    System Settings
    zoom.us
)

for (( i=1; i<="${#UNMANAGED[@]}"; i++ )); do 
    yabai -m rule --add label="unmanage_${UNMANAGED[(( $i - 1 ))]}" app="^${UNMANAGED[(( $i - 1 ))]}.*$" manage=off border=off
done

COMMS=(
    Microsoft Teams
    Mail
    Messages
    Spark
    Mail
    Discord
    Dialpad
)

for (( i=1; i<="${#COMMS[@]}"; i++ )); do 
    yabai -m rule --add label="comms_${COMMS[(( $i - 1 ))]}" app="^${COMMS[(( $i - 1 ))]}.*$" space=comms
done

STICKY=(
    Authy Desktop
    Bitwarden
    System Preferences
    System Settings
)

for (( i=1; i<="${#STICKY[@]}"; i++ )); do 
    yabai -m rule --add label="sticky_${STICKY[(( $i - 1 ))]}" app="^${STICKY[(( $i - 1 ))]}.*$" sticky=on
done

yabai -m rule --add app="kitty" title="KUAKE" manage=off border=off grid=8:8:0:0:8:3 
yabai -m rule --add app="kitty" title="^Wallpaper$" manage=off border=off sticky=on grid=8:8:0:5:8:3 opacity=0.85
yabai -m rule --add app="^LinkedNotesUIService$" title="^Window$" manage=off border=off
yabai -m rule --add app="^Microsoft Remote Desktop$" title!="Microsoft Remote Desktop" native-fullscreen=on
yabai -m rule --add app="^Music$" space=media
yabai -m rule --add app="^Spark$" title!="^Spark - .*$" manage=off border=off sticky=on
yabai -m rule --add app="^Screens$" title!="Screens Library" native-fullscreen=on
# TODO: Test this
yabai -m rule --add app="^Screen Sharing$" title!="^Screen Sharing$" native-fullscreen=on

# SIGNALS
yabai -m signal --add event=window_created app="Code" action="source ${HOME}/.config/bin/helper && auto_stack Code"
yabai -m signal --add event=window_created app="Firefox" title!="— Private Browsing$" action="source ${HOME}/.config/bin/helper && auto_stack Firefox"
yabai -m signal --add event=window_title_changed app="Firefox" title="- noVNC$" action="yabai -m window ${WINDOW_ID} --toggle native-fullscreen"
yabai -m signal --add event=window_created app="Firefox" title="Picture-in-Picture" action="yabai -m window ${WINDOW_ID} --toggle border --toggle float --toggle sticky"
yabai -m signal --add event=window_created action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=window_destroyed action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=window_focused action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=space_changed action="sketchybar -m --trigger yabai_window &> /dev/null;"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger yabai_window &> /dev/null"

# TODO: Cleanup
# Rules
# yabai -m rule --add label="DialpadSplash" app="Dialpad" title=".*- Loading.*$" manage=off layer=below space=scratch opacity=0.0


