#!/usr/bin/env bash

# Dracula
BACKGROUND="#282a36"
CURRENT_LINE="#44475a"
FOREGROUND="#f8f8f2"	
COMMENT="#6272a4"	
CYAN="#8be9fd"
GREEN="#50fa7b"
ORANGE="#ffb86c"	
PINK="#ff79c6"
PURPLE="#bd93f9"	
RED="#ff5555"
YELLOW="#f1fa8c"

# DuskFox (Rose Pine)
RP_BACKGROUND="#232136"
RP_FOREGROUND="#e0def4"
RP_COLOR0="#393552"
RP_COLOR1="#eb6f92"
RP_COLOR2="#a3be8c"
RP_COLOR3="#f6c177"
RP_COLOR4="#569fba"
RP_COLOR5="#c4a7e7"
RP_COLOR6="#9ccfd8"
RP_COLOR7="#e0def4"
RP_COLOR8="#47407d"
RP_COLOR9="#f083a2"
RP_COLOR10="#b1d196"
RP_COLOR11="#f9cb8c"
RP_COLOR12="#65b1cd"
RP_COLOR13="#ccb1ed"
RP_COLOR14="#a6dae3"
RP_COLOR15="#e2e0f7"

# Everforest
COLOR9="#2f383e" # bg0,       palette1 dark (medium)
BACKGROUND="#d3c6aa" # fg,        palette2 dark
COLOR0="#859289" # grey1,     palette2 dark
COLOR1="#7fbbb3" # blue,      palette2 dark
COLOR2="#d699b6" # purple,    palette2 dark
COLOR3="#dbbc7f" # yellow,    palette2 dark
COLOR4="#83c092" # aqua,      palette2 dark
COLOR5="#e69875" # orange,    palette2 dark
COLOR6="#a7c080" # green,     palette2 dark
COLOR7="#e67e80" # red,       palette2 dark
FOREGROUND="#eaedc8" # bg_visual, palette1 dark (medium)
COLOR8="#374247" # bg1,       palette1 dark (medium)
COLOR10="#4a555b" # bg3,       palette1 dark (medium)
COLOR11="#9da9a0" # grey2,     palette2 dark
COLOR12="#e4e1cd" # bg3,       palette1 light (medium)
COLOR13="#fdf6e3" # bg0,       palette1 light (medium)

