#!/usr/bin/env bash
config_dir="$HOME/.config/sketchybar/configs"

# General
## Bar and Defaults
sh $config_dir/defaults
## Custom Events

# Left
## Modal Indicator
sh $config_dir/modal
## Spaces
sh $config_dir/spaces
## Window Title
sh $config_dir/focus
## Stack Indicator
sh $config_dir/stack

# Right
## Battery
sh $config_dir/battery
## Date and Time
sh $config_dir/time
## Music
sh $config_dir/music

sketchybar --update