#!/usr/bin/env bash

# D E F A U L T S

sketchybar --bar                              \
position=top                                  \
height=38                                     \
color="0xFF000000"                            \
display=main                                  \
corner_radius=0                               \
padding_left=22                               \
padding_right=16                              \
--default                                     \
icon.font="VictorMono Nerd Font:Bold:18.0"    \
label.font="VictorMono Nerd Font:Italic:18.0" \
associated_display=1                       
