#!/usr/bin/env bash

# Colors
source $HOME/.config/sketchybar/colors

# S C R I P T
# TODO: Create Script to toggle Modes 
SCRIPT=" 
"
# C O N F 
sketchybar -m --add item modal_indicator left                 \
              --set modal_indicator                           \
                icon="N"                                      \
                icon.color="0xFF${COLOR3:1}"                  \
                icon.padding_left=12                          \
                icon.padding_right=12                         \
                background.color="0x96${COLOR8:1}"            \
                background.height=24                          \
                background.padding_left=-9                    \
                background.padding_right=9                    \
                background.corner_radius=4                    \
                script="$SCRIPT"                              \
              --subscribe modal_indicator mouse.clicked
