# Z e l l i j 
mouse_mode: true
pane_frames: true
theme: rose-pine
themes:
  rose-pine:
    fg: 8    # background Color for satusbar keys
    bg: 0    # Color for Highlight
    black: 235  # Tab Text
    gray: 0   # Bar Background
    red: 3    # Status bar Key Text
    green: 3 # Tab Background | Active Pane
    yellow: 0
    blue: 0
    magenta: 0
    cyan: 0
    white: 5 # Session Text | inactive Pane
    orange: 1 # Modifier Key Text Selected Pane for Modification
ui:
  pane_frames:
    rounded_corners: true
