#!/usr/bin/env bash

stack_index=$(yabai -m query --windows --window | jq -r ."[\"stack-index\"]")
if [[ stack_index -eq 0 ]]; then
    sketchybar --set stack drawing=off
    exit 0
fi

num_stacked=$(yabai -m query --windows --window stack.last | jq -r ."[\"stack-index\"]")

sketchybar --set stack                                      \
    label=$(printf "[%s/%s]" "$stack_index" "$num_stacked") \
    drawing=on