#!/usr/bin/env bash
case $@ in
"Brave Browser")
  icon_result=":brave_browser:"
  ;;
"Keyboard Maestro")
  icon_result=":keyboard_maestro:"
  ;;
"Min")
  icon_result=":min_browser:"
  ;;
"Final Cut Pro")
  icon_result=":final_cut_pro:"
  ;;
"FaceTime")
  icon_result="􀱱"
  ;;
"Affinity Publisher")
  icon_result=":affinity_publisher:"
  ;;
"Messages" | "Nachrichten")
  icon_result="􀌥"
  ;;
"Tweetbot" | "Twitter")
  icon_result=":twitter:"
  ;;
"ClickUp")
  icon_result=":click_up:"
  ;;
"KeePassXC")
  icon_result=":kee_pass_x_c:"
  ;;
"Microsoft Edge")
  icon_result=":microsoft_edge:"
  ;;
"VLC")
  icon_result=":vlc:"
  ;;
"Emacs")
  icon_result=":emacs:"
  ;;
"Thunderbird")
  icon_result=":thunderbird:"
  ;;
"Notes")
  icon_result=":notes:"
  ;;
"Caprine")
  icon_result=":caprine:"
  ;;
"Zulip")
  icon_result=":zulip:"
  ;;
"Spark")
  icon_result="􀍙"
  ;;
"Microsoft To Do" | "Things")
  icon_result=""
  ;;
"DEVONthink 3")
  icon_result=":devonthink3:"
  ;;
"GitHub Desktop")
  icon_result=":git_hub:"
  ;;
"App Store")
  icon_result=""
  ;;
"Chromium" | "Google Chrome" | "Google Chrome Canary")
  icon_result=""
  ;;
"zoom.us")
  icon_result=":zoom:"
  ;;
"MoneyMoney")
  icon_result=":bank:"
  ;;
"Color Picker")
  icon_result=":color_picker:"
  ;;
"Microsoft Word")
  icon_result=":microsoft_word:"
  ;;
"Iris")
  icon_result=":iris:"
  ;;
"WebStorm")
  icon_result=":web_storm:"
  ;;
"Neovide" | "MacVim" | "Vim" | "VimR")
  icon_result=":vim:"
  ;;
"Sublime Text")
  icon_result=":sublime_text:"
  ;;
"PomoDone App")
  icon_result=":pomodone:"
  ;;
"Setapp")
  icon_result=":setapp:"
  ;;
"qutebrowser")
  icon_result=":qute_browser:"
  ;;
"Mattermost")
  icon_result=":mattermost:"
  ;;
"Notability")
  icon_result=":notability:"
  ;;
"WhatsApp")
  icon_result=":whats_app:"
  ;;
"OBS")
  icon_result=":obsstudio:"
  ;;
"Parallels Desktop")
  icon_result=":parallels:"
  ;;
"VMware Fusion")
  icon_result=":vmware_fusion:"
  ;;
"Pine")
  icon_result=":pine:"
  ;;
"Microsoft Excel")
  icon_result=":microsoft_excel:"
  ;;
"Microsoft PowerPoint")
  icon_result=":microsoft_power_point:"
  ;;
"Matlab")
  icon_result=":matlab:"
  ;;
"Numbers")
  icon_result=":numbers:"
  ;;
"Default")
  icon_result=":default:"
  ;;
"Element")
  icon_result=":element:"
  ;;
"Bear")
  icon_result=":bear:"
  ;;
"TeamSpeak 3")
  icon_result=":team_speak:"
  ;;
"Airmail")
  icon_result="􀍙"
  ;;
"Firefox Developer Edition" | "Firefox Nightly")
  icon_result="󰈹"
  ;;
"Trello")
  icon_result=":trello:"
  ;;
"TickTick")
  icon_result=":tick_tick:"
  ;;
"Notion")
  icon_result=":notion:"
  ;;
"Live")
  icon_result=":ableton:"
  ;;
"Evernote Legacy")
  icon_result=":evernote_legacy:"
  ;;
"Calendar" | "Fantastical")
  icon_result=""
  ;;
"Android Studio")
  icon_result=":android_studio:"
  ;;
"Xcode")
  icon_result=":xcode:"
  ;;
"Slack")
  icon_result=":slack:"
  ;;
"Sequel Pro")
  icon_result=":sequel_pro:"
  ;;
"Bitwarden"|"Authy Desktop")
  icon_result="󰢁"
  ;;
"System Preferences" | "System Settings")
  icon_result=""
  ;;
"Discord" | "Discord Canary" | "Discord PTB")
  icon_result="󰙯"
  ;;
"Vivaldi")
  icon_result=":vivaldi:"
  ;;
"Firefox")
  icon_result="󰈹"
  ;;
"Skype")
  icon_result=":skype:"
  ;;
"Dropbox")
  icon_result=":dropbox:"
  ;;
"微信")
  icon_result=":wechat:"
  ;;
"Typora")
  icon_result=":text:"
  ;;
"Blender")
  icon_result=":blender:"
  ;;
"Canary Mail" | "HEY" | "Mail" | "Mailspring" | "MailMate" | "邮件")
  icon_result="􀍙"
  ;;
"Safari" | "Safari Technology Preview")
  icon_result="􀍙"
  ;;
"Telegram")
  icon_result=":telegram:"
  ;;
"Keynote")
  icon_result=":keynote:"
  ;;
"Reeder")
  icon_result=":reeder5:"
  ;;
"Spotify")
  icon_result=":spotify:"
  ;;
"MAMP" | "MAMP PRO")
  icon_result=":mamp:"
  ;;
"Figma")
  icon_result=":figma:"
  ;;
"Joplin")
  icon_result=":joplin:"
  ;;
"Spotlight")
  icon_result="󱁵"
  ;;
"Music")
  icon_result="󰎈"
  ;;
"Insomnia")
  icon_result=":insomnia:"
  ;;
"TIDAL")
  icon_result=":tidal:"
  ;;
"Alfred")
  icon_result="󱁵"
  ;;
"Pages")
  icon_result=":pages:"
  ;;
"Folx")
  icon_result=":folx:"
  ;;
"Android Messages")
  icon_result=":android_messages:"
  ;;
"mpv")
  icon_result=":mpv:"
  ;;
"网易云音乐")
  icon_result=":netease_music:"
  ;;
"Transmit")
  icon_result=":transmit:"
  ;;
"Pi-hole Remote")
  icon_result=":pihole:"
  ;;
"Nova")
  icon_result=":nova:"
  ;;
"Affinity Designer")
  icon_result=":affinity_designer:"
  ;;
"IntelliJ IDEA")
  icon_result=":idea:"
  ;;
"Drafts")
  icon_result=":drafts:"
  ;;
"Audacity")
  icon_result=":audacity:"
  ;;
"Affinity Photo")
  icon_result=":affinity_photo:"
  ;;
"Atom")
  icon_result=":atom:"
  ;;
"Obsidian")
  icon_result="󰼭"
  ;;
"Dialpad")
  icon_result="􀟜"
;;
"CleanMyMac X")
  icon_result=":desktop:"
  ;;
"Zotero")
  icon_result=":zotero:"
  ;;
"Todoist")
  icon_result=":todoist:"
  ;;
"LibreWolf")
  icon_result=":libre_wolf:"
  ;;
"Grammarly Editor")
  icon_result=":grammarly:"
  ;;
"OmniFocus")
  icon_result=":omni_focus:"
  ;;
"Reminders")
  icon_result=""
  ;;
"Preview" | "Skim" | "zathura" | "PDF Expert")
  icon_result=""
  ;;
"1Password 7")
  icon_result=":one_password:"
  ;;
"Code" | "Code - Insiders")
  icon_result="󰨞"
  ;;
"VSCodium")
  icon_result="󰨞"
  ;;
"Tower")
  icon_result=":tower:"
  ;;
"Calibre")
  icon_result=":book:"
  ;;
"Finder" | "访达")
  icon_result="󰀶"
  ;;
"Linear")
  icon_result=":linear:"
  ;;
"League of Legends")
  icon_result=":league_of_legends:"
  ;;
"Zeplin")
  icon_result=":zeplin:"
  ;;
"Signal")
  icon_result=":signal:"
  ;;
"Podcasts")
  icon_result=":podcasts:"
  ;;
"Alacritty" | "Hyper" | "iTerm2" | "kitty" | "Terminal" | "WezTerm")
  icon_result=""
  ;;
"Tor Browser")
  icon_result=":tor_browser:"
  ;;
"Kakoune")
  icon_result=":kakoune:"
  ;;
"GrandTotal" | "Receipts")
  icon_result=":dollar:"
  ;;
"Sketch")
  icon_result=":sketch:"
  ;;
"Sequel Ace")
  icon_result=":sequel_ace:"
  ;;
"false Mostly Cloudy"| "false Cloudy" | "false Partly Cloudy")
  icon_result="󰼱"
  ;;
"false Slight Chance Rain Showers")
  icon_result=""
  ;;
"true Rain Showers Likely" | "true Rain Showers" | "true Chance Rain Showers")
  icon_result=""
  ;;
"false Patchy Fog"| "false Areas Of Fog" | "false Widespread Fog")
  icon_result=""
  ;;
"true Sunny")
  icon_result=""
  ;;
"false Clear" | "false Mostly Clear")
  icon_result="󰖔"
  ;;
*)
  icon_result=""
  ;;
esac
echo $icon_result