#!/usr/bin/env bash

# D E F A U L T S

sketchybar -m --bar                           \
position=top                                  \
height=39                                     \
color="0xFF000000"                            \
display=all                                   \
--default                                     \
icon.font="VictorMono Nerd Font:Bold:18.0"    \
label.font="VictorMono Nerd Font:Italic:18.0" \
associated_display=1                       
